"""add user_notification_settings table

Revision ID: 29c0bab0a0d1
Revises: ca3e0b283b1c
Create Date: 2025-07-14 22:46:01.998645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c0bab0a0d1'
down_revision = 'ca3e0b283b1c'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('win_notify', sa.Boolean(), nullable=False),
    sa.Column('start_notify', sa.Boolean(), nullable=False),
    sa.Column('finish_notify', sa.Boolean(), nullable=False),
    sa.Column('widget_notify', sa.Boolean(), nullable=False),
    sa.Column('banner', sa.Boolean(), nullable=False),
    sa.Column('sound', sa.Boolean(), nullable=False),
    sa.Column('dnd_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    # ### end Alembic commands ###
