"""initial

Revision ID: ca3e0b283b1c
Revises: 
Create Date: 2025-07-14 13:40:05.043767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3e0b283b1c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vk_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('membersCount', sa.String(), nullable=False),
    sa.Column('raffleCount', sa.String(), nullable=False),
    sa.Column('adminType', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'MODERATOR', 'MEMBER', 'ADVERTISER', name='admintype'), nullable=False),
    sa.Column('avatarUrl', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('YELLOW', 'GREEN', 'RED', name='status'), nullable=False),
    sa.Column('buttonDesc', sa.String(), nullable=False),
    sa.Column('stateText', sa.Enum('ACTIVE', 'INACTIVE', 'ATTENTION', 'ERROR', name='statetext'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_id'), 'communities', ['id'], unique=False)
    op.create_index(op.f('ix_communities_vk_user_id'), 'communities', ['vk_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('COMPLETED', 'WARNING', 'ERROR', name='notificationtype'), nullable=False),
    sa.Column('raffleId', sa.Integer(), nullable=True),
    sa.Column('participantsCount', sa.Integer(), nullable=True),
    sa.Column('winners', sa.JSON(), nullable=True),
    sa.Column('reasonEnd', sa.String(), nullable=True),
    sa.Column('warningTitle', sa.String(), nullable=True),
    sa.Column('warningDescription', sa.JSON(), nullable=True),
    sa.Column('errorTitle', sa.String(), nullable=True),
    sa.Column('errorDescription', sa.String(), nullable=True),
    sa.Column('new', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('raffles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vk_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('contest_text', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('require_community_subscription', sa.Boolean(), nullable=False),
    sa.Column('require_telegram_subscription', sa.Boolean(), nullable=False),
    sa.Column('telegram_channel', sa.String(), nullable=True),
    sa.Column('required_communities', sa.JSON(), nullable=False),
    sa.Column('partner_tags', sa.JSON(), nullable=False),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('blacklist_participants', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('publish_results', sa.Boolean(), nullable=False),
    sa.Column('hide_participants_count', sa.Boolean(), nullable=False),
    sa.Column('exclude_me', sa.Boolean(), nullable=False),
    sa.Column('exclude_admins', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='rafflestatus'), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffles_community_id'), 'raffles', ['community_id'], unique=False)
    op.create_index(op.f('ix_raffles_end_date'), 'raffles', ['end_date'], unique=False)
    op.create_index(op.f('ix_raffles_id'), 'raffles', ['id'], unique=False)
    op.create_index(op.f('ix_raffles_name'), 'raffles', ['name'], unique=False)
    op.create_index(op.f('ix_raffles_start_date'), 'raffles', ['start_date'], unique=False)
    op.create_index(op.f('ix_raffles_status'), 'raffles', ['status'], unique=False)
    op.create_index(op.f('ix_raffles_vk_user_id'), 'raffles', ['vk_user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raffles_vk_user_id'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_status'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_start_date'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_name'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_id'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_end_date'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_community_id'), table_name='raffles')
    op.drop_table('raffles')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_communities_vk_user_id'), table_name='communities')
    op.drop_index(op.f('ix_communities_id'), table_name='communities')
    op.drop_table('communities')
    # ### end Alembic commands ###
